# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x9c\x01\n\x05\x45vent\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\"\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x11.agent.AudioChunkH\x00\x12\'\n\ntranscript\x18\x03 \x01(\x0b\x32\x11.agent.TranscriptH\x00\x12\'\n\x07\x63ontrol\x18\x04 \x01(\x0b\x32\x14.agent.ControlSignalH\x00\x42\t\n\x07payload\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\",\n\nTranscript\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\"~\n\rControlSignal\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.agent.ControlSignal.SignalType\">\n\nSignalType\x12\x11\n\rSTART_SESSION\x10\x00\x12\x0f\n\x0b\x45ND_SESSION\x10\x01\x12\x0c\n\x08\x42\x41RGE_IN\x10\x02\x32<\n\nVoiceAgent\x12.\n\x0cStreamEvents\x12\x0c.agent.Event\x1a\x0c.agent.Event(\x01\x30\x01\x42/Z-voice-runtime/orchestrator-go/generated;agentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-voice-runtime/orchestrator-go/generated;agent'
  _globals['_EVENT']._serialized_start=23
  _globals['_EVENT']._serialized_end=179
  _globals['_AUDIOCHUNK']._serialized_start=181
  _globals['_AUDIOCHUNK']._serialized_end=207
  _globals['_TRANSCRIPT']._serialized_start=209
  _globals['_TRANSCRIPT']._serialized_end=253
  _globals['_CONTROLSIGNAL']._serialized_start=255
  _globals['_CONTROLSIGNAL']._serialized_end=381
  _globals['_CONTROLSIGNAL_SIGNALTYPE']._serialized_start=319
  _globals['_CONTROLSIGNAL_SIGNALTYPE']._serialized_end=381
  _globals['_VOICEAGENT']._serialized_start=383
  _globals['_VOICEAGENT']._serialized_end=443
# @@protoc_insertion_point(module_scope)
